<?php

use App\Prize;
use Illuminate\Database\Seeder;

class PrizeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $priceList = [
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'PANTALLA DE 32"',
            'MESA DE CRISTAL',
            'RIZADOR DE CABELLO',
            'RIZADOR DE CABELLO',
            'RIZADOR DE CABELLO',
            'RIZADOR DE CABELLO',
            'RIZADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'ALACIADOR DE CABELLO',
            'COMEDOR',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'JUEGO DE UTENSILIOS DE COCINA',
            'RECORTADORA DE BARBA Y BIGOTE',
            'RECORTADORA DE BARBA Y BIGOTE',
            'RECORTADORA DE BARBA Y BIGOTE',
            'RECORTADORA DE BARBA Y BIGOTE',
            'RECORTADORA DE BARBA Y BIGOTE',
            'EDREDÓN',
            'EDREDÓN',
            'EDREDÓN',
            'EDREDÓN',
            'EDREDÓN',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'FRAZADA ',
            'OLLA DE PRESIÓN',
            'OLLA DE PRESIÓN',
            'OLLA DE PRESIÓN',
            'OLLA DE PRESIÓN',
            'OLLA DE PRESIÓN',
            'SET DE COSMETICOS DE 9 PIEZAS',
            'SET DE COSMETICOS DE 9 PIEZAS',
            'SET DE COSMETICOS DE 9 PIEZAS',
            'SET DE COSMETICOS DE 9 PIEZAS',
            'SET DE COSMETICOS DE 9 PIEZAS',
            'SET DE BROCHAS PROFESIONALES DE 7 PIEZAS',
            'SET DE BROCHAS PROFESIONALES DE 7 PIEZAS',
            'SET DE BROCHAS PROFESIONALES DE 7 PIEZAS',
            'SET DE BROCHAS PROFESIONALES DE 7 PIEZAS',
            'SET DE BROCHAS PROFESIONALES DE 7 PIEZAS',
            'SET DE ARTICULOS DE BELLEZA DE 55 PIEZAS',
            'SET DE ARTICULOS DE BELLEZA DE 55 PIEZAS',
            'SET DE ARTICULOS DE BELLEZA DE 55 PIEZAS',
            'SET DE ARTICULOS DE BELLEZA DE 55 PIEZAS',
            'SET DE ARTICULOS DE BELLEZA DE 55 PIEZAS',
            'SET DE BROCHAS PROFESIONALES DE 11 PIEZAS',
            'ESTUCHE DE MAQUILLAJE DE 93 PIEZAS',
            'JUEGO DE JARRA Y VASOS DE 5 PIEZAS',
            'JUEGO DE JARRA Y VASOS DE 5 PIEZAS',
            'JUEGO DE JARRA Y VASOS DE 5 PIEZAS',
            'JUEGO DE JARRA Y VASOS DE 5 PIEZAS',
            'JUEGO DE COSMETIQUERAS DE 3 PIEZAS',
            'JUEGO DE COSMETIQUERAS DE 3 PIEZAS',
            'JUEGO DE COSMETIQUERAS DE 3 PIEZAS',
            'JUEGO DE COSMETIQUERAS DE 3 PIEZAS',
            'TETERA SILBANTE CON TAPA',
            'TETERA SILBANTE CON TAPA',
            'TETERA SILBANTE CON TAPA',
            'BOCINA CON BLUETOOTH',
            'BOCINA CON BLUETOOTH',
            'BOCINA CON BLUETOOTH',
            'BOCINA CON BLUETOOTH',
            'JUEGO DE PELUQUERIA DE 17 PIEZAS',
            'JUEGO DE PELUQUERIA DE 17 PIEZAS',
            'JUEGO DE PELUQUERIA DE 17 PIEZAS',
            'RASURADA ELÉCTRICA DE 5 PIEZAS',
            'RASURADA ELÉCTRICA DE 5 PIEZAS',
            'RASURADA ELÉCTRICA DE 5 PIEZAS',
            'RASURADA ELÉCTRICA DE 5 PIEZAS',
            'RASURADA ELÉCTRICA DE 5 PIEZAS',
            'RASURADO ELECTRCA DE 1 PIEZA',
            'RASURADO ELECTRCA DE 1 PIEZA',
            'RASURADO ELECTRCA DE 1 PIEZA',
            'RASURADO ELECTRCA DE 1 PIEZA',
            'EXPRIMIDOR DE CÍTRICOS',
            'EXPRIMIDOR DE CÍTRICOS',
            'EXPRIMIDOR DE CÍTRICOS',
            'EXPRIMIDOR DE CÍTRICOS',
            'EXPRIMIDOR DE CÍTRICOS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE TAZONES Y VASOS DE 12 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'MINI COMPONENTE AMPLIFICADO',
            'MINI COMPONENTE AMPLIFICADO',
            'MINI COMPONENTE AMPLIFICADO',
            'BATERIA VILLALINDA DE ACERO DE PIEZAS',
            'BATERIA VILLALINDA DE ACERO DE PIEZAS',
            'BATERIA VILLALINDA DE ACERO DE PIEZAS',
            'BRAUN ',
            'BRAUN ',
            'BRAUN ',
            'BRAUN ',
            'BRAUN ',
            'CALEFACTOR DE HÁLOGENO',
            'CALEFACTOR DE HÁLOGENO',
            'CALEFACTOR DE HÁLOGENO',
            'CALEFACTOR DE HÁLOGENO',
            'HORNO ELÉCTRICO',
            'HORNO ELÉCTRICO',
            'OLLA DE COCCIÓN LENTA CON PIZARRA',
            'OLLA DE COCCIÓN LENTA CON PIZARRA',
            'SISTEMA PORTÁTIL DE AUDIO ',
            'SISTEMA PORTÁTIL DE AUDIO ',
            'SISTEMA PORTÁTIL DE AUDIO ',
            'CAFETERA',
            'CAFETERA',
            'CAFETERA',
            'CAFETERA',
            'CAFETERA',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'JUEGO DE TAZONES DE VIDRIO DE 4 PIEZAS',
            'JUEGO DE TAZONES DE VIDRIO DE 4 PIEZAS',
            'JUEGO DE TAZONES DE VIDRIO DE 4 PIEZAS',
            'JUEGO DE BOCINAS MULTIMEDIA',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'JUEGO DE VASOS, PLATOS Y CUCHARAS DE 12 PIEZAS',
            'PARRILLA ELÉCTRICA DE UN QUEMADOR',
            'PARRILLA ELÉCTRICA DE UN QUEMADOR',
            'PARRILLA ELÉCTRICA DE UN QUEMADOR',
            'PARRILLA ELÉCTRICA DE UN QUEMADOR',
            'PARRILLA ELÉCTRICA DE UN QUEMADOR',
            'PARRILLA ELÉCTRICA DE UN QUEMADOR',
            'TOSTADORA DE PAN',
            'TOSTADORA DE PAN',
            'SANDWICHERA XPRESS',
            'SANDWICHERA XPRESS',
            'SANDWICHERA XPRESS',
            'SANDWICHERA XPRESS',
            'SET ROASTER DE 9 PIEZAS',
            'SET ROASTER DE 9 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'LICUADORA',
            'LICUADORA',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'JUEGO DE VASOS DE VIDRIO DE 20 PIEZAS',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'PLANCHA DE VAPOR',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'TABLET i700',
            'COMPUTADORA PORTÁTIL ACER',
            'BATIDORA DE MANO',
            'BATIDORA DE MANO',
            'BATIDORA DE MANO',
            'BATIDORA DE MANO',
            'MICROONDAS',
            'MICROONDAS',
            'MICROONDAS',
            'BARRA DE SONIDO ATVIO',
            'BARRA DE SONIDO ATVIO',
            'BARRA DE SONIDO SANYO',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'BATERIA DE COCINA DE 5 PIEZAS',
            'ASPIRADORA DE BASTÓN',
            'ASPIRADORA DE BASTÓN',
            'KIT DE PELUQUERÍA DE 10 PIEZAS',
            'KIT DE PELUQUERÍA DE 10 PIEZAS',
            'KIT DE PELUQUERÍA DE 10 PIEZAS',
            'KIT DE PELUQUERÍA DE 10 PIEZAS',
            'JUEGO DE VASOS DE 10 PIEZAS',
            'JUEGO DE VASOS DE 10 PIEZAS',
            'JUEGO DE VASOS DE 10 PIEZAS',
            'JUEGO DE VASOS DE 10 PIEZAS',
            'JUEGO DE CUBIERTOS DE 24 PIEZAS',
            'JUEGO DE CUBIERTOS DE 24 PIEZAS',
            'JUEGO DE CUBIERTOS DE 24 PIEZAS',
            'JUEGO DE CUBIERTOS DE 24 PIEZAS',
            'JUEGO DE CUBIERTOS DE 24 PIEZAS',
            'BATERIA DE COCINA DE 9 PIEZAS',
            'BATERIA DE COCINA DE 9 PIEZAS',
            'BATERIA DE COCINA DE 9 PIEZAS',
            'BATERIA DE COCINA DE 9 PIEZAS',
            'VAJILLA DE VIDRIO DE 12 PIEZAS',
            'VAJILLA DE VIDRIO DE 12 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'JUEGO DE VASOS DE 8 PIEZAS',
            'JUEGO DE CUBIERTOS DE 20 PIEZAS',
            'JUEGO DE CUBIERTOS DE 20 PIEZAS',
            'JUEGO DE CUBIERTOS DE 20 PIEZAS',
            'JUEGO DE CUBIERTOS DE 20 PIEZAS',
            'JUEGO DE CUBIERTOS DE 20 PIEZAS',
            'JUEGO DE CUBIERTOS DE 20 PIEZAS',
            'JUEGO DE CUBIERTOS DE 20 PIEZAS',
            'SECADORA DE CABELLO TIMCO',
            'SECADORA DE CABELLO TIMCO',
            'SECADORA DE CABELLO TIMCO',
            'SECADORA DE CABELLO TIMCO',
            'SECADORA DE CABELLO TIMCO',
            'SECADORA DE CABELLO REVLON',
            'SECADORA DE CABELLO REVLON',
            'SECADORA DE CABELLO REVLON',
            'BICICLETA FIJA',
            'SOFA CAMA',
            'PANTALLA DE 43"',
            'PANTALLA DE 43"',
            'PANTALLA DE 43"',
            'PANTALLA DE 43"',
            'REFRIGERADOR',
            'REFRIGERADOR',
            'LAVADORA',
            'LAVADORA',
            'ESTUFA',
            'ESTUFA',
            'LICUADORA',
            'LICUADORA',
            'LICUADORA',
            'LICUADORA',
            'LICUADORA',
            'LICUADORA',
            'LICUADORA',
            'COLCHON',
            'COLCHON',
            'COLCHON',
            'COLCHON',
        ];

        foreach ($priceList as $key => $priceName) {
           Prize::create([
                'name' => $priceName,
            ]);
        }
    }
}
