<?php

use App\Prize;
use Illuminate\Database\Seeder;

class PrizeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $priceList = [
            ['337','5 Refractarios de Vidrio y 5 tapas de plastico Glazé',1],
            ['338','5 Refractarios de Vidrio y 5 tapas de plastico Glazé',2],
            ['339','5 Refractarios de Vidrio y 5 tapas de plastico Glazé',4],
            ['340','5 Refractarios de Vidrio y 5 tapas de plastico Glazé',3],
            ['341','5 Refractarios de Vidrio y 5 tapas de plastico Glazé',1],
            ['369','Abanico de Techo Harbor Breeze',1],
            ['172','abanico de techo harbor breeze.',2],
            ['531','Abanico Harbor',1],
            ['168','Abanico Taurus',1],
            ['175','Abanico Taurus',1],
            ['179','Abanico Taurus',1],
            ['310','alaciadora con placas de ceramica timco.',1],
            ['311','alaciadora con placas de ceramica timco.',1],
            ['312','alaciadora con placas de ceramica timco.',1],
            ['335','Alaciadora Revlon',2],
            ['336','Alaciadora Revlon',3],
            ['152','Alaciadora Taurus.',4],
            ['153','Alaciadora Taurus.',2],
            ['154','Alaciadora Taurus.',3],
            ['155','Alaciadora Taurus.',4],
            ['253','Arrocera c/tapa Tramontina',2],
            ['254','Arrocera c/tapa Tramontina',1],
            ['418','Asador Outdoor trend',3],
            ['360','Aspiradora',1],
            ['423','Aspiradora Dirt Devil',2],
            ['449','Aspiradora Mikel¨S',3],
            ['490','Aspiradora Mikel¨S',2],
            ['134','audifonos stf sound',3],
            ['135','audifonos stf sound',4],
            ['136','audifonos stf sound',2],
            ['137','audifonos stf sound',4],
            ['138','audifonos stf sound',1],
            ['365','Audifonos STF Sound',4],
            ['397','Audifonos STF Sound',3],
            ['406','Audifonos STF Sound',2],
            ['421','Audifonos STF Sound',1],
            ['422','Audifonos STF Sound',3],
            ['558','Audifonos STF Sound',4],
            ['559','Audifonos STF Sound',2],
            ['560','Audifonos STF Sound',4],
            ['178','Azador de Carbón Outdoor Trend',1],
            ['9','Bafle Recargable (Bocina) Concierto mio',2],
            ['352','Bajilla Ebro (12pz)',3],
            ['353','Bajilla Ebro (12pz)',4],
            ['358','Bajilla Santa Anita (16pz)',2],
            ['371','Bandeja Rectangular PYR-O-REY',1],
            ['372','Bandeja Rectangular PYR-O-REY',3],
            ['429','Bandeja Rectangular PYR-O-REY',4],
            ['548','Baño de burbujas para pies Revlon',3],
            ['604','Baño de burbujas Revlon',1],
            ['373','Bateria CINSA (7pz)',2],
            ['534','Bateria CINSA (7pz)',3],
            ['6','Bateria de Cocina (9pz) Ekos',1],
            ['480','Bateria de Cocina (9pz) Ekos',3],
            ['481','Bateria de Cocina (9pz) Ekos',4],
            ['618','Bateria de cocina 20pz Main Stays',1],
            ['619','Bateria de cocina 20pz Main Stays',3],
            ['107','bateria ecko 9 pzs.',2],
            ['308','batidora de imersion sunbeam.',1],
            ['299','batidora de imersion taurus.',3],
            ['300','batidora de imersion taurus.',4],
            ['301','batidora de imersion taurus.',2],
            ['302','batidora de imersion taurus.',1],
            ['303','batidora de imersion taurus.',4],
            ['304','batidora de imersion taurus.',2],
            ['305','batidora de imersion taurus.',4],
            ['306','batidora de imersion taurus.',3],
            ['307','batidora de imersion taurus.',3],
            ['519','Batidora Tradition',1],
            ['367','Batidora Traditions',2],
            ['375','Batidora Traditions',4],
            ['376','Batidora Traditions',4],
            ['165','bocina bafle.',3],
            ['166','bocina bafle.',2],
            ['167','bocina bafle.',1],
            ['91','bocina bafle.?cm',3],
            ['99','bocina bafle.?cm',1],
            ['430','Bocina Bluetooth Kaiser',2],
            ['431','Bocina Bluetooth Kaiser',2],
            ['148','bocina green leaf.',1],
            ['171','bocina green leaf.',2],
            ['444','Bocina green leaf.',1],
            ['8','Bocina Inalambrica Green Leaf',1],
            ['468','Bocina Inalambrica Green Leaf',2],
            ['522','Bocina Logitech',2],
            ['128','bocinas logitech.',3],
            ['510','Bocinas logitech.',4],
            ['580','Bolsa Cosmetic Lab',4],
            ['581','Bolsa Cosmetic Lab',3],
            ['536','Bolsita negra Cosmetic Lab',4],
            ['552','Bolsita negra Cosmetic Lab',2],
            ['586','Bolsita negra Cosmetic Lab',2],
            ['662','Brochas 6pz',3],
            ['664','Brochas 6pz',4],
            ['663','Brochas 8pz',3],
            ['118','brown sunbeam',4],
            ['119','brown sunbeam',3],
            ['120','brown sunbeam',4],
            ['121','brown sunbeam',3],
            ['255','Cable Pasa Corriente 120 a 12 V cc 2.5 m multitop',4],
            ['256','Cable Pasa Corriente 120 a 12 V cc 2.5 m multitop',3],
            ['48','Cafetera Best Home',4],
            ['49','Cafetera Best Home',3],
            ['189','Cafetera Best Home',4],
            ['190','Cafetera Best Home',2],
            ['366','Cafetera Best Home',2],
            ['392','Cafetera Best Home',2],
            ['386','Cafetera Best Home',4],
            ['433','Cafetera Best Home',2],
            ['442','Cafetera Best Home',2],
            ['443','Cafetera Best Home',1],
            ['85','cafetera best home.',2],
            ['110','cafetera best home.',3],
            ['144','cafetera best home.',4],
            ['466','Cafetera de goteo Best Home',2],
            ['216','caja de herramientas 17" truper.',3],
            ['217','caja de herramientas 17" truper.',2],
            ['218','caja de herramientas 17" truper.',4],
            ['489','Calefactor Best Home',1],
            ['57','Calefactor de halógeno Best Home',3],
            ['251','Calentador c/tapa de Vidrio CINSA 1.7 Litros',4],
            ['252','Calentador c/tapa de Vidrio CINSA 1.7 Litros',2],
            ['354','Calentón Best Home',1],
            ['361','Calentón Best Home',4],
            ['507','Calentón Best Home',2],
            ['374','Class Bows (5pz) Libbey',1],
            ['159','cobertor con borrega.',4],
            ['243','Cobertor Fusionado Estampado con Borrega Soft Sensations King Size',2],
            ['244','Cobertor Fusionado Estampado con Borrega Soft Sensations Matrimonial',1],
            ['113','cobijita cuadrada.',4],
            ['196','Colcha con cojin Mainstays',2],
            ['237','Colcha con Cojin Mainstays',2],
            ['229','colchon ortopedico individual master',3],
            ['230','colchon ortopedico individual master',4],
            ['231','Colchón Ortopedico Individual Master',2],
            ['232','Colchón Super Ortopedico Individual Master',1],
            ['233','Colchón Super Ortopedico Individual Master',3],
            ['535','Comedor',1],
            ['124','copa cristar 4 pzs.',2],
            ['125','copa cristar 4 pzs.',2],
            ['504','Copa cristar 4 pzs.',4],
            ['501','Copas cristar (4pz)',2],
            ['364','Copas de Cristal (4pz)',1],
            ['390','Copas de Cristal (4pz)',3],
            ['72','cortadora de cabello taurus',4],
            ['73','cortadora de cabello taurus',2],
            ['74','cortadora de cabello taurus',1],
            ['147','cortadora de cabello taurus',3],
            ['416','Cortadora de cabello taurus',4],
            ['425','cortadora de cabello taurus',2],
            ['426','cortadora de cabello taurus',1],
            ['440','cortadora de cabello taurus',3],
            ['470','Cortadora de cabello taurus',4],
            ['471','Cortadora de cabello taurus',4],
            ['520','Cortadora de cabello taurus',1],
            ['582','Cosmetiquera',3],
            ['583','Cosmetiquera',2],
            ['584','Cosmetiquera',3],
            ['585','Cosmetiquera',2],
            ['653','Cosmetiquera',1],
            ['659','Cosmetiquera',3],
            ['643','Cosmetiquera Cosmetic Lab',3],
            ['599','Cosmetiquera cristalina Cosmetic Lab',2],
            ['600','Cosmetiquera gris con blanco Cosmetic Lab',3],
            ['567','Cosmetiquera rosa Cosmetic Lab',2],
            ['568','Cosmetiquera rosa Cosmetic Lab',2],
            ['569','Cosmetiquera rosa Cosmetic Lab',3],
            ['570','Cosmetiquera rosa Cosmetic Lab',4],
            ['537','Cosmetiquera The Best',1],
            ['84','crock. Pot olla electrica.',3],
            ['546','Cuadro flotante Main Stayns 24 fotos (Blanco)',2],
            ['545','Cuadro flotante Main Stayns 24 fotos (Negro)',3],
            ['417','Cubiertos SK (16pz)',1],
            ['176','Delineadora de Barba Timco',1],
            ['645','Desarmador de trinquete Stanley',3],
            ['641','Desarmadores truper 5pz',1],
            ['642','Desarmadores truper 5pz',2],
            ['434','Duo Cups T-Fal',3],
            ['592','DVD con Karaoke',2],
            ['593','DVD con Karaoke',1],
            ['241','Edredón de Microfibra Matrimonial Mainstays',3],
            ['242','Edredón de Microfibra Matrimonial Mainstays',4],
            ['158','edredon mainstays.',5],
            ['191','Edredon Viajero',2],
            ['195','Edredon Viajero 926',3],
            ['235','Edredón Viajero NANO (1.15 x 1.50) mts beige',4],
            ['236','Edredón Viajero NANO (1.15 x 1.50) mts café',1],
            ['239','Edredrón Doble Vista Individual Essentails Home',2],
            ['240','Edredrón Doble Vista Individual Essentails Home',3],
            ['238','Edredrón Matrimonial Mainstays',4],
            ['414','Escurridor de platos',1],
            ['437','Escurridor de platos Hamilton Beach',2],
            ['438','Escurridor de platos Hamilton Beach',3],
            ['439','Escurridor de platos Hamilton Beach',4],
            ['633','Estuche de brochas 6pz',1],
            ['3','Estufa Acros',2],
            ['108','estufa para bufe black + decker.',3],
            ['1','Estufa Ranger IEM',4],
            ['385','Exprimidor electrico proctor siler',1],
            ['529','Exprimidor electrico proctor siler',2],
            ['530','Exprimidor electrico proctor siler',3],
            ['399','Frasada',1],
            ['400','Frasada',2],
            ['401','Frasada',3],
            ['402','Frasada',4],
            ['403','Frasada',1],
            ['404','Frasada',2],
            ['511','Frazada Main Stayns',3],
            ['538','Frazada Main Stayns',1],
            ['539','Frazada Main Stayns',2],
            ['540','Frazada Main Stayns',3],
            ['541','Frazada Main Stayns',4],
            ['566','Frazada Main Stayns',1],
            ['370','Frazada Mainstays',2],
            ['156','frazada mainstays.',4],
            ['157','frazada mainstays.',1],
            ['163','frazada mainstays.',2],
            ['112','frazada throw',3],
            ['245','Frazada Viajera NANO',4],
            ['219','hielera 12 latas 10.5 litros nyc.',1],
            ['220','hielera 12 latas 10.5 litros nyc.',2],
            ['486','hielera 12 latas nyc.',3],
            ['225','hielera 54 lata 45.5 litros nyc.',4],
            ['223','hielera coleman 34 litros',1],
            ['224','hielera coleman 34 litros',2],
            ['221','hielera igloo 11 litros',3],
            ['222','hielera igloo 11 litros',3],
            ['532','Horno Black and Decker',1],
            ['203','horno de microondas hamilton Beach.',2],
            ['180','Horno Electrico Best Home',3],
            ['487','Horno microondas Hamilton',4],
            ['350','Jarra y Vasos Crisa (5pz)',1],
            ['448','Jarra y Vasos Crisa (5pz)',2],
            ['459','Jarra y Vasos Crisa (7pz)',3],
            ['66','Jarra y Vasos Crisia (5pz)',4],
            ['184','Jarra y Vasos Crisia (7pz)',1],
            ['349','Juedo de Cubiertos Mainstays',2],
            ['26','Juego Crisa (8pz)',3],
            ['461','Juego Crisa (8pz)',3],
            ['602','Juego de 6 llaves pretul',1],
            ['647','Juego de 6 llaves pretul',2],
            ['101','juego de agua bassic',3],
            ['102','juego de agua bassic',4],
            ['379','Juego de Agua Bassic (7pz)',1],
            ['380','Juego de Agua Bassic (7pz)',2],
            ['395','Juego de agua Bassic (7pz)',3],
            ['419','Juego de Agua Bassic (7pz)',4],
            ['12','Juego de Agua Neptuno (7pz)',1],
            ['23','Juego de Agua Neptuno (7pz)',2],
            ['29','Juego de Agua Neptuno (7pz)',4],
            ['75','juego de agua neptuno 7 pzas.',1],
            ['76','juego de agua neptuno 7 pzas.',2],
            ['658','Juego de baño',3],
            ['660','Juego de baño',3],
            ['639','Juego de baño 7pz Aromanice',1],
            ['640','Juego de baño 7pz Aromanice',2],
            ['553','Juego de baño Aromanice',3],
            ['554','Juego de baño Aromanice',4],
            ['555','Juego de baño Aromanice',1],
            ['644','Juego de baño Aromanice',2],
            ['465','Juego de Bar de vidrio (8pz)',4],
            ['485','Juego de Bar de vidrio (8pz)',1],
            ['183','Juego de Bar Libbey (8pz)',1],
            ['505','Juego de Bar Libbey (8pz)',2],
            ['561','Juego de brochas 7pz Xpert Beauty',3],
            ['562','Juego de brochas 7pz Xpert Beauty',4],
            ['563','Juego de brochas 7pz Xpert Beauty',1],
            ['564','Juego de brochas 7pz Xpert Beauty',2],
            ['565','Juego de brochas 7pz Xpert Beauty',4],
            ['608','Juego de brochas 8pz',1],
            ['609','Juego de brochas 8pz',2],
            ['610','Juego de brochas 8pz',1],
            ['188','Juego de Cocina (4pz) Ekco',2],
            ['104','juego de cocina 4 pzs ecko.',4],
            ['405','Juego de Cubiertos (16pz)',1],
            ['257','Juego de Cubiertos (16pz) Mainstays',2],
            ['258','Juego de Cubiertos (16pz) Mainstays',3],
            ['259','Juego de Cubiertos (16pz) Mainstays',4],
            ['260','Juego de Cubiertos (16pz) Mainstays',1],
            ['261','Juego de Cubiertos (16pz) Mainstays',2],
            ['293','juego de cubiertos 16 pcs mainstays.',3],
            ['309','juego de cubiertos 16 pzas simple kitchen.',4],
            ['284','juego de cubiertos 16 pzs gibson.',1],
            ['285','juego de cubiertos 16 pzs gibson.',2],
            ['286','juego de cubiertos 16 pzs gibson.',4],
            ['287','juego de cubiertos 16 pzs gibson.',1],
            ['288','juego de cubiertos 16 pzs gibson.',2],
            ['289','juego de cubiertos 16 pzs gibson.',4],
            ['290','juego de cubiertos 16 pzs gibson.',1],
            ['291','juego de cubiertos 16 pzs gibson.',2],
            ['63','Juego de Cubiertos Sk (16pz)',3],
            ['64','Juego de Cubiertos Sk (16pz)',4],
            ['276','juego de cucharas 5 pzs para cocinar.',1],
            ['277','juego de cucharas 5 pzs para cocinar.',2],
            ['278','juego de cucharas 5 pzs para cocinar.',3],
            ['279','juego de cucharas 5 pzs para cocinar.',4],
            ['280','juego de cucharas 5 pzs para cocinar.',1],
            ['281','juego de cucharas 5 pzs para cocinar.',2],
            ['282','juego de cucharas 5 pzs para cocinar.',3],
            ['283','juego de cucharas 5 pzs para cocinar.',3],
            ['383','Juego de cuchillos  top choice',4],
            ['488','Juego de cuchillos 12 piezas Tramontina',1],
            ['262','juego de cuchillos 4 pcs tramontina.',2],
            ['263','juego de cuchillos 4 pcs tramontina.',3],
            ['264','juego de cuchillos 4 pcs tramontina.',4],
            ['265','juego de cuchillos 4 pcs tramontina.',1],
            ['266','juego de cuchillos 4 pcs tramontina.',2],
            ['267','juego de cuchillos 4 pcs tramontina.',3],
            ['268','juego de cuchillos 4 pcs tramontina.',1],
            ['269','juego de cuchillos 4 pcs tramontina.',2],
            ['270','juego de cuchillos 4 pcs tramontina.',3],
            ['271','juego de cuchillos 4 pcs tramontina.',4],
            ['272','juego de cuchillos 4 pcs tramontina.',1],
            ['273','juego de cuchillos 4 pcs tramontina.',2],
            ['274','juego de cuchillos 4 pcs tramontina.',3],
            ['275','juego de cuchillos 4 pcs tramontina.',4],
            ['292','juego de cuchillos 4 pcs tramontina.',1],
            ['44','Juego de cuchillos Top Choice',2],
            ['182','Juego de cuchillos Top Choice',3],
            ['199','Juego de Cuchillos Top Choice',4],
            ['646','Juego de desarmador de puntas',1],
            ['638','Juego de desarmador truper',2],
            ['650','Juego de desatornillador truper',3],
            ['321','juego de herramientas 15 pzas workpro.',4],
            ['427','Juego de herramientas pretul  (70pz)',1],
            ['428','Juego de herramientas pretul  (70pz)',2],
            ['41','Juego de jarras y vasos crisa',3],
            ['42','Juego de jarras y vasos crisa',4],
            ['607','Juego de maquillaje 37pz',1],
            ['572','Juego de maquillaje 37pz C.L.',2],
            ['573','Juego de maquillaje 37pz C.L.',3],
            ['634','Juego de maquillaje 41pz',4],
            ['635','Juego de maquillaje 41pz',1],
            ['636','Juego de maquillaje 41pz',2],
            ['637','Juego de maquillaje 41pz',3],
            ['318','juego de peluqueria 18 pzas conair.',4],
            ['319','juego de peluqueria 18 pzas conair.',1],
            ['31','Juego de puntas p/desarmador Truper',2],
            ['32','Juego de puntas p/desarmador Truper',3],
            ['411','Juego de puntas y dados Truper (25pz)',4],
            ['193','Juego de recipientes Best Home (3pz)',1],
            ['194','Juego de recipientes Best Home (3pz)',1],
            ['67','Juego de Sartenes (3pz) Ecko',2],
            ['68','Juego de Sartenes (3pz) Ecko',3],
            ['69','Juego de Sartenes (3pz) Ecko',4],
            ['70','Juego de Sartenes (4pz) Ecko',1],
            ['477','Juego de servir Jarra con vaso',2],
            ['469','Juego de vasos (12pz) Main Stayns',3],
            ['478','Juego de vasos (6pz9 glaze',4],
            ['632','Juego de vasos 6pz Glaze',2],
            ['620','Juego de vasos 8pz Main Stays',3],
            ['621','Juego de vasos 8pz Main Stays',4],
            ['622','Juego de vasos 8pz Main Stays',3],
            ['623','Juego de vasos 8pz Main Stays',1],
            ['624','Juego de vasos 8pz Main Stays',2],
            ['625','Juego de vasos 8pz Vsantos',3],
            ['626','Juego de vasos 8pz Vsantos',4],
            ['627','Juego de vasos 8pz Vsantos',1],
            ['467','Juego de vasos de España (10pz) Santos',2],
            ['458','Juego de vasos Vsantos  (10pz)',3],
            ['7','Juego de Vasos, Platos y Cucharas (12 pz) Santa Elenita',4],
            ['456','Juego para agua valencia (6pz)',1],
            ['38','Juguera Electrica Hometech',2],
            ['39','Juguera Electrica Hometech',3],
            ['71','Juguera Electrica Hometech',4],
            ['197','Juguera Electrica Hometech',1],
            ['457','Kit de peluqueria Timco (10pz)',2],
            ['116','lampara de buro best home.',3],
            ['435','lampara de buro best home.',3],
            ['4','Lavadora Acros',1],
            ['201','lavadora automatica daewo 14kg.',2],
            ['204','lavadora automatica daewo 19 kg.',3],
            ['200','lavadora automatica daewo 19kg.',4],
            ['143','licuadora americam',2],
            ['10','Licuadora American',1],
            ['20','Licuadora American',2],
            ['21','Licuadora American',1],
            ['22','Licuadora American',2],
            ['34','Licuadora American',3],
            ['36','Licuadora American',1],
            ['37','Licuadora American',2],
            ['462','Licuadora American',3],
            ['89','licuadora american.',4],
            ['142','licuadora oster',3],
            ['151','licuadora oster',1],
            ['177','Licuadora Oster',2],
            ['483','Licuadora Oster',3],
            ['198','Licuadora Taurus',4],
            ['359','Licuadora Taurus',1],
            ['388','Licuadora Taurus',2],
            ['574','Make up collection 89pz',3],
            ['575','Make up collection 89pz',4],
            ['579','Make up collection 89pz',1],
            ['576','Make up collection 96pz',2],
            ['577','Make up collection 96pz',3],
            ['578','Make up collection 96pz',4],
            ['226','maleta etco travel.',3],
            ['227','maleta etco travel.',1],
            ['174','Maleta LQ Chica',2],
            ['173','Maleta LQ Mediana',3],
            ['59','Manta de Polar Mainstays',4],
            ['60','Manta de Polar Mainstays',1],
            ['61','Manta de Polar Mainstays',2],
            ['342','Manta de Polar Mainstays',3],
            ['343','Manta de Polar Mainstays',4],
            ['344','Manta de Polar Mainstays',3],
            ['345','Manta de Polar Mainstays',4],
            ['346','Manta de Polar Mainstays',2],
            ['347','Manta de Polar Mainstays',3],
            ['348','Manta de Polar Mainstays',1],
            ['591','Manta de Polar Mainstays',2],
            ['652','Manta Mainstays azul',3],
            ['651','Manta Mainstays gris',4],
            ['648','Manta polar Azul',1],
            ['657','Manta polar café',2],
            ['656','Manta polar gris',3],
            ['649','Manta polar verde',4],
            ['398','Maquina para el cabello Timco',1],
            ['549','Maquina para palomitas sunbeam',2],
            ['603','Matraka con dados 16pz Santul',3],
            ['105','microondas daewoo.',2],
            ['106','microondas daewoo.',2],
            ['202','microondas daewoo.',2],
            ['249','Olla de Aluminio c/tapa Hometrends 1.9 litros',3],
            ['250','Olla de Aluminio c/tapa Hometrends 1.9 litros',4],
            ['247','Olla de Aluminio c/tapa Hometrends 2.8 litros',1],
            ['248','Olla de Aluminio c/tapa Hometrends 2.8 litros',2],
            ['246','Olla de Aluminio c/tapa Hometrends 4.7 litros',3],
            ['160','olla de coccion lenta black & decker.',4],
            ['492','olla de lento cocimiento Black and decker',1],
            ['473','Olla de lento cocimiento hamilton beach',2],
            ['464','Olla Lento Cocimiento Black Decker',3],
            ['181','Olla Lento Cocimiento Hamilton Beach',4],
            ['378','Olla Lento Cocimiento Hamilton Beach',1],
            ['187','Parrilla Electrica Michel',2],
            ['368','Parrilla Electrica Michel',3],
            ['77','parrilla electrica michel.',4],
            ['149','parrilla electrica taurus',1],
            ['150','parrilla electrica taurus',2],
            ['377','Parrilla Michel',3],
            ['82','parrillera electrica michel.',4],
            ['408','Perfiladora tauros',1],
            ['409','Perfiladora tauros',2],
            ['410','Perfiladora tauros',3],
            ['11','Plancha Black & Decker',4],
            ['14','Plancha Black & Decker',1],
            ['15','Plancha Black & Decker',2],
            ['16','Plancha Black & Decker',3],
            ['17','Plancha Black & Decker',4],
            ['18','Plancha Black & Decker',1],
            ['78','plancha black & decker.',2],
            ['79','plancha black & decker.',3],
            ['80','plancha black & decker.',4],
            ['103','plancha black & decker.',1],
            ['19','Plancha Taurus',2],
            ['122','plancha taurus.',3],
            ['123','plancha taurus.',4],
            ['500','Platos Crisa (12pz)',1],
            ['43','Platos elite (3pz)',2],
            ['450','Platos porcelana elit (3pz)',3],
            ['30','Proctor Silex (exprimidor)',4],
            ['384','Rasuradora timco Men',1],
            ['407','Razones crisa (8pz)',2],
            ['357','Recamara',3],
            ['451','Recipientes Best Home (3pz)',4],
            ['313','recortadora de barba y bigote conair.',1],
            ['314','recortadora de barba y bigote conair.',2],
            ['315','recortadora de barba y bigote conair.',3],
            ['316','recortadora de barba y bigote conair.',4],
            ['317','recortadora de barba y bigote conair.',1],
            ['320','recortadora de barba y bigote conair.',2],
            ['514','Recortadora de barba y bigote conair.',2],
            ['2','Refrigerador Mabe',3],
            ['542','Reloj de pared',4],
            ['590','Reloj Home Trends',1],
            ['322','rizador de cabello taurus.',2],
            ['323','rizador de cabello taurus.',3],
            ['324','rizador de cabello taurus.',4],
            ['325','rizador de cabello taurus.',1],
            ['326','rizador de cabello taurus.',2],
            ['327','rizador de cabello taurus.',3],
            ['328','rizador de cabello taurus.',1],
            ['329','rizador de cabello taurus.',2],
            ['330','rizador de cabello taurus.',3],
            ['331','rizador de cabello taurus.',1],
            ['362','Ropero',2],
            ['50','Sandwichera Black & Decker',4],
            ['62','Sandwichera Black & Decker',4],
            ['81','sandwichera black and decker',3],
            ['40','Santa Elenita (16pz)',2],
            ['52','Sarten electrico Holstein',1],
            ['351','Sarten electrico Holstein',4],
            ['356','Secadora Conair',3],
            ['139','secadora conair.',3],
            ['140','secadora conair.',1],
            ['332','Secadora Mediana Conair',2],
            ['333','Secadora Mediana Conair',3],
            ['334','Secadora Mediana Conair',4],
            ['164','secadora timco.',1],
            ['297','set de accesorios para asar 3 pzas acero inoxidable.',2],
            ['298','set de accesorios para asar 3 pzas acero inoxidable.',3],
            ['296','set de accesorios para asar 3 pzas. Acero inoxidable.',4],
            ['294','set de accesorios para asar 3 pzas. Outdoor trend',1],
            ['295','set de accesorios para asar 3 pzas. Outdoor trend',2],
            ['571','Set de brochas 6pz Cosmetic Lab',3],
            ['543','Set de cubiertos 24 piezas',4],
            ['544','Set de cubiertos 24 piezas',1],
            ['594','Set de cuchillos Acero Inoxidable',2],
            ['595','Set de cuchillos Acero Inoxidable',3],
            ['596','Set de cuchillos Acero Inoxidable',2],
            ['493','Set de tazas (3pz) Main Stayns',1],
            ['192','Set de Tazones (3pz)',2],
            ['513','Set de Tazones (3pz) Main Stayns',3],
            ['598','Set de tazones 3pz',4],
            ['631','Set de tazones 3pz Main Stays',1],
            ['460','Set de Tazones Mainstays  (3pz)',2],
            ['661','Set de utencilios Backyard Grill',4],
            ['597','Set de utencilios de bambu',4],
            ['654','Set de utencilios de bambu',3],
            ['655','Set de utencilios de bambu',1],
            ['611','Set de vaso 8 pz Crisa',2],
            ['612','Set de vaso 8 pz Crisa',3],
            ['613','Set de vaso 8 pz Crisa',4],
            ['614','Set de vaso 8 pz Crisa',1],
            ['615','Set de vaso 8 pz Crisa',2],
            ['517','Set Oasis (2pz)',3],
            ['605','Silla mariposa Main Stays',4],
            ['606','Silla mariposa Main Stays',1],
            ['5','Smart TV RCA 40"',2],
            ['228','sofacama hometrends.',3],
            ['601','Stanley Control Grip 29pz',4],
            ['382','Tablet tech pad "7"',1],
            ['387','Tablet tech pad "7"',2],
            ['455','Tablet tech pad "7"',3],
            ['518','Tablet tech pad "7"',4],
            ['129','tablet tech pad 7"',1],
            ['130','tablet tech pad 7"',4],
            ['131','tablet tech pad 7"',3],
            ['132','tablet tech pad 7"',2],
            ['133','tablet tech pad 7"',1],
            ['412','tazones crisa',4],
            ['413','tazones crisa',3],
            ['420','Tazones crisa (8pz)',2],
            ['452','Tazones crisa (8pz)',1],
            ['497','Tazones crisa (8pz)',4],
            ['90','tazones crisa 8 pzas.',3],
            ['92','tazones crisa 8 pzas.',2],
            ['56','Tazones de Vidrio Crisa',1],
            ['415','Tazones Maintavs (3pz)',4],
            ['441','Tazones Maintavs (3pz)',3],
            ['498','Tazones Maintays (3pz)',2],
            ['234','Televición Led Smart FHD TV 40" RCA',1],
            ['215','television orizzonte 43" smart.',4],
            ['205','television quaroni 32" led.',3],
            ['206','television quaroni 32" led.',2],
            ['207','television quaroni 32" led.',1],
            ['208','television quaroni 32" led.',2],
            ['209','television quaroni 32" led.',4],
            ['210','television quaroni 32" led.',2],
            ['211','television quaroni 32" led.',3],
            ['212','television quaroni 32" led.',4],
            ['213','television quaroni 32" led.',2],
            ['214','television quaroni 32" led.',4],
            ['111','tetera best home.',1],
            ['33','Tetera Electrica RCA',2],
            ['35','Tetera RCA',1],
            ['169','Tetera RCA',3],
            ['393','Tetera RCA',1],
            ['463','Tetera RCA',2],
            ['117','t-fal duo cups.',2],
            ['355','Tostador Best Home',3],
            ['479','Tostador de pan Taurus',1],
            ['145','tostador taurus',2],
            ['185','Tostador Taurus',3],
            ['186','Tostador Taurus',4],
            ['550','Tres espejos Home creations',1],
            ['551','Tres espejos Home creations',2],
            ['484','Vajilla (12pz) Bormioli',3],
            ['491','Vajilla (12pz) Crisa',4],
            ['51','Vajilla (12pz) Venecia',1],
            ['474','Vajilla (12pz)Bormioli',2],
            ['616','Vajilla 12pz Andalucita',3],
            ['617','Vajilla 12pz Home Gallery',4],
            ['503','Vajilla Bicrila (12pz)',1],
            ['502','Vajilla Crisa (12pz)',2],
            ['556','Vajilla Crisa (12pz)',3],
            ['557','Vajilla Crisa (8pz)',4],
            ['630','Vajilla de porcelana 12pz Home Gallery',1],
            ['628','Vajilla de vidrio 12pz crisa',2],
            ['629','Vajilla de vidrio 12pz crisa',3],
            ['446','Vajilla Ebro (12pz)',3],
            ['447','Vajilla Ebro (12pz)',1],
            ['472','vajilla para 4 personas opal glass',1],
            ['476','Vajilla para 5 personas Bormioli',3],
            ['58','Vajilla Santa Elenita (16pz)',2],
            ['88','vajilla venecia 12 pzas.',1],
            ['93','vajilla venecia 12 pzas.',1],
            ['94','vajilla venecia 12 pzas.',2],
            ['98','vajilla venecia 12 pzas.',3],
            ['516','vajilla venecia 12 pzas.',4],
            ['65','Vajilla Vicria (12pz)',1],
            ['389','Vajilla vicrila (12pz)',2],
            ['432','Vajilla vicrila (12pz)',3],
            ['521','Vajillas Santa Anita (16pz)',4],
            ['127','vallija 12 pzs crisa.',1],
            ['547','Vaporera 5.2 lts Hammilton',2],
            ['496','Vaso Bassic (8pz)',3],
            ['53','Vasos (6pz) Bassic',4],
            ['54','Vasos (6pz) Bassic',2],
            ['55','Vasos (6pz) Bassic',1],
            ['24','Vasos (8pz) Bassic',3],
            ['25','Vasos (8pz) Bassic',1],
            ['13','Vasos (8pz) Crisa',3],
            ['391','Vasos Bassic (6pz)',4],
            ['394','Vasos Bassic (6pz)',3],
            ['396','Vasos Bassic (6pz)',1],
            ['436','Vasos Bassic (8pz)',4],
            ['445','Vasos Bassic (8pz)',4],
            ['515','Vasos Bassic (8pz)',4],
            ['170','vasos bassic 6 pzas.',1],
            ['87','vasos bassic 8 pzas.',2],
            ['95','vasos bassic 8 pzas.',3],
            ['28','Vasos Crisa (8pz)',1],
            ['161','Vasos Crisa (8pz)',2],
            ['162','Vasos Crisa (8pz)',3],
            ['83','vasos crisa 8 pzas.',1],
            ['86','vasos crisa 8 pzas.',2],
            ['96','vasos crisa 8 pzas.',3],
            ['97','vasos crisa 8 pzas.',1],
            ['100','vasos crisa 8 pzas.',1],
            ['146','vasos crisa 8 pzas.',2],
            ['424','Vasos España (10pz)',3],
            ['499','Vasos España (10pz)',1],
            ['509','Vasos España (10pz)',2],
            ['512','Vasos España (10pz)',3],
            ['381','Vasos glaze',1],
            ['453','Vasos Glaze (6pz)',2],
            ['454','Vasos Glaze (6pz)',1],
            ['494','Vasos Glaze (6pz)',2],
            ['495','Vasos Glaze (6pz)',1],
            ['506','Vasos Glaze (6pz)',2],
            ['508','Vasos Glaze (6pz)',1],
            ['523','Vasos glaze (6pz)',4],
            ['524','Vasos glaze (6pz)',3],
            ['525','Vasos glaze (6pz)',2],
            ['526','Vasos glaze (6pz)',3],
            ['527','Vasos glaze (6pz)',4],
            ['528','Vasos glaze (6pz)',2],
            ['533','Vasos Glaze (6pz)',3],
            ['45','Vasos Glazé (6pz)',4],
            ['46','Vasos Glazé (6pz)',2],
            ['47','Vasos Glazé (6pz)',3],
            ['114','vasos glazé 6 pzs',4],
            ['115','vasos glazé 6 pzs',2],
            ['126','vasos glazé 6 pzs',3],
            ['141','vasos glazé 6 pzs',2],
            ['109','vasos vicrila 8 pzas.',3],
            ['363','Ventilador Taurus',2],
            ['27','Vitrolero (3 tLts)',3],
            ['482','Vitrolero practico Jema flex',2],
            ['587','Zapatero 2 niveles',3],
            ['588','Zapatero 2 niveles',2],
            ['589','Zapatero 2 niveles',3],
            ['475','Juego de 6 vasos de cristal',4]
        ];

        foreach ($priceList as $key => $priceName) {
           Prize::create([
                'article_no' => $priceName[0],
                'name' => $priceName[1],
                'batch' => $priceName[2],
            ]);
        }
    }
}
